monorepo_root = true
[monorepo]
config_roots = [".", "packages/*", "websites/*", "telemetry", "assets"]

[tools]
# TypeScript
bun = "latest"
node = "lts"

# Python
python = "3.10.20"
uv = "latest"

# Tools
fnox = "latest"
gh = "latest" # GitHub CLI
ruff = "latest" # Python formatter
shfmt = "latest" # .sh formatter
oxfmt = "latest" # TS formatter
"pipx:pyprojectsort" = "latest" # pyproject.toml formatter
"pipx:wheel" = "latest" # Python wheel builder
ollama = "latest"
watchexec = "latest" # File system watcher

[env]
'_'.source = "scripts/env.sh"
# Tool envs
LANGCHAIN_CODEX_LITTERBOX_UPLOAD = true # Enable image auto-uploading for Codex
MISE_EXPERIMENTAL = true # Enable monorepo root support
OPENCODE_CONFIG_DIR = "./.agents"
FORCE_COLOR = "1" # Force colors, i.e., for `bun --filter test`
DOCKER_CLI_CMD = "docker"

# Default tracing envs. To enable set ALUMNIUM_TRACE=true.
OTEL_SERVICE_NAME = "alumnium"
OTEL_EXPORTER_OTLP_ENDPOINT = "http://127.0.0.1:4318"
OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"

[settings]
env_shell_expand = true # Allow using "${VAR}" in values
lockfile = true
idiomatic_version_file_enable_tools = ["node", "bun", "potery", "python"]

[tasks.install]
run = [
  { task = "install/mise" },
  { task = "install/bun" },
  { task = "//packages/typescript:install" },
  { task = "//packages/python:install" },
  { task = "//websites/docs:install" },
]

[tasks."install/mise"]
run = "mise install"

[tasks."install/bun"]
run = "bun install"
# NOTE: No need to specify sources and outputs as `bun install` is faster at tracking them than mise.

[tasks."install/playwright"]
# NOTE: Each package might have its own Playwright version and expect a particular browser versions,
# so we need to run the installation for each package separately.
run = [
  { task = "//packages/java:install/playwright" },
  { task = "//packages/typescript:install/playwright" },
  { task = "//packages/python:install/playwright" },
]
# NOTE: It prompts for sudo to install OS dependencies
raw = true

[tasks."install/ollama"]
description = "Installs default Ollama provider model. Requires Ollama to be installed and running."
run = "ollama pull $(mise //packages/typescript:get-ollama-model)"

[tasks.build]
depends = [
  "//packages/java:build",
  "//packages/python:build",
  "//packages/typescript:build",
  "//websites/docs:build",
]
description = "Build all"

[tasks."dev/cli"]
usage = '''
arg "[args]" var=#true default=""
'''
run = [
  { task = "//packages/typescript:dev/cli", args = [
    "{{usage.args | join(sep=' ')}}",
  ] },
]
quiet = true
raw = true

[tasks."dev/server"]
run = [{ task = "//packages/typescript:dev/server" }]
quiet = true
raw = true

[tasks."dev/mcp"]
run = [{ task = "//packages/typescript:dev/mcp" }]
quiet = true
raw = true

[tasks."dev/mcp:inspect"]
run = [{ task = "//packages/typescript:dev/mcp:inspect" }]

[tasks."clean"]
run = "rm -rf ./.alumnium"
depends_post = ["//packages/typescript:clean", "//packages/python:clean"]

[tasks."clear/cache"]
description = "Clears all Alumnium LLM cache."
run = "rm -rf ./.alumnium/cache"
depends_post = [
  "//packages/typescript:clear/cache",
  "//packages/python:clear/cache",
]

[tasks.format]
depends = [
  "//packages/java:format",
  "//packages/python:format",
  "//packages/typescript:format",
]

[tasks."format/check"]
depends = [
  "//packages/java:format/check",
  "//packages/python:format/check",
  "//packages/typescript:format/check",
]

[tasks.types]
depends = ["types/ts", "//packages/java:types", "//packages/python:types"]

[tasks.lint]
description = "Lint all packages"
depends = [
  "//packages/java:lint",
  "//packages/python:lint",
  "//packages/typescript:lint",
]

[tasks."lint/fix"]
description = "Fix linting issues in all packages"
depends = ["//packages/typescript:lint/fix", "//packages/python:lint/fix"]

[tasks."types/ts"]
run = "bun run tsc --build"

[tasks."types/ts:watch"]
run = "bun run tsc --build --watch"

[tasks."test/unit"]
depends = [
  "//packages/java:test/unit",
  "//packages/python:test/unit",
  "//packages/typescript:test/unit",
]

[tasks."test/system"]
depends = [
  "//packages/java:test/system",
  "//packages/python:test/system",
  "//packages/typescript:test/system",
]

[tasks."test/package"]
description = "Run all (npm, pip, maven) package tests"
depends = [
  "//packages/java:test/package",
  "//packages/python:test/package",
  "//packages/typescript:test/package",
]

[tasks.version]
run = { task = "//packages/typescript:version" }
quiet = true
raw = true

[tasks."docker/build"]
description = "Build Docker image"
depends = ["//packages/typescript:build"]
run = "docker build --build-arg VERSION=$(mise //packages/typescript:version) -t alumnium:latest ."

[tasks."docker/run"]
description = "Run Docker container"
run = "docker run --rm -p 8013:8013 alumnium:latest"
