#!/usr/bin/env bun

// This script generates helper files for the Alumnium single-file executable.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadAgentPrompts } from "../src/server/agents/prompts/prompts.ts";
import { computeCursorSdkManifest } from "../src/standalone/cursorSdkManifest.ts";

const curName = fileURLToPath(import.meta.url);
const curDir = path.dirname(curName);

const bundles = await Promise.all([
  bundleDriverScripts(),
  bundleAgentPrompts(),
  bundleCursorSdkManifest(),
]);

// NOTE: We write paths to stdout to use as oxfmt args
const bundlePaths = bundles
  .map((bundlePath) => JSON.stringify(bundlePath))
  .join(" ");
console.write(bundlePaths);

async function bundleDriverScripts() {
  const scriptsDir = path.resolve(curDir, "../src/drivers/scripts");

  const waiterSource = await fs.readFile(
    path.resolve(scriptsDir, "waiter.js"),
    "utf-8",
  );

  const bundlePath = path.resolve(scriptsDir, "bundledScripts.ts");
  await fs.writeFile(
    bundlePath,
    `// This file is auto-generated by scripts/generate-bundles.ts. Do not edit it directly.

export const waiterScriptSource = ${JSON.stringify(waiterSource)};
`,
  );
  return bundlePath;
}

async function bundleCursorSdkManifest() {
  const lockPath = path.resolve(curDir, "../../../bun.lock");
  const lockText = await fs.readFile(lockPath, "utf-8");
  // bun.lock is JSONC; the only non-JSON syntax it uses is trailing commas,
  // and no value in it can contain ",}" / ",]" sequences.
  const lock = JSON.parse(lockText.replace(/,(\s*[}\]])/g, "$1"));

  const manifest = computeCursorSdkManifest(lock);

  const bundlePath = path.resolve(
    curDir,
    "../src/standalone/cursorSdkVendorManifest.ts",
  );
  await fs.writeFile(
    bundlePath,
    `// This file is auto-generated by scripts/generate-bundles.ts. Do not edit it directly.

import type { CursorSdkVendorManifest } from "./cursorSdkManifest.ts";

export const cursorSdkVendorManifest : CursorSdkVendorManifest = ${JSON.stringify(manifest, null, 2)};
`,
  );
  return bundlePath;
}

async function bundleAgentPrompts() {
  const prompts = await loadAgentPrompts();

  const bundlePath = path.resolve(
    curDir,
    "../src/server/agents/prompts/bundledPrompts.ts",
  );
  await fs.writeFile(
    bundlePath,
    `// This file is auto-generated by scripts/generate-bundles.ts. Do not edit it directly.

import type { AgentPrompts } from "./prompts.ts";

export const agentPrompts : AgentPrompts = ${JSON.stringify(prompts, null, 2)};
`,
  );
  return bundlePath;
}
